/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.hbasesoft.framework.wechat.bean.msg;

import com.hbasesoft.framework.db.core.BaseEntity;

public class WxUserInfo extends BaseEntity {

    /**
     * serialVersionUID <br>
     */
    private static final long serialVersionUID = 4056068007408028615L;

    private String nickName; // optional

    private String gender; // optional

    private String headImg; // optional

    private String provice; // optional

    private String city; // optional

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getHeadImg() {
        return headImg;
    }

    public void setHeadImg(String headImg) {
        this.headImg = headImg;
    }

    public String getProvice() {
        return provice;
    }

    public void setProvice(String provice) {
        this.provice = provice;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

}
