SELECT M.RESOURCE_ID,
       M.PARENT_RESOURCE_ID,
       M.SEQ,
       M.MENU_NAME,
       M.URL,
       M.IS_LEAF,
       M.ICON_URL
FROM MENU M, RESOURCES R
WHERE M.RESOURCE_ID = R.RESOURCE_ID
AND R.MODULE_CODE IN (:moduleCode)
ORDER BY M.PARENT_RESOURCE_ID ASC, M.SEQ ASC