SELECT M.MENU_ID
  FROM MENU M, URL_RESOURCE U
 WHERE M.RESOURCE_ID = U.RESOURCE_ID
   AND U.MODULE_CODE IN (:moduleCode)
   AND M.IS_LEAF = 'Y'
   AND U.EXECUTE_CLASS = :class
   AND U.EXECUTE_METHOD = :method