SELECT M.RESOURCE_ID,
       M.PARENT_RESOURCE_ID,
       M.SEQ,
       M.MENU_NAME,
       M.URL,
       M.IS_LEAF,
       M.ICON_URL
  FROM MENU M,
       (SELECT O.RESOURCE_ID
          FROM OPERATOR_RESOURCE O, RESOURCES R
         WHERE O.RESOURCE_ID = R.RESOURCE_ID
           AND R.MODULE_CODE IN (:moduleCode)
           AND R.RESOURCE_TYPE = 'M'
           AND O.OPERATOR_ID = :operateId
        UNION
        SELECT RR.RESOURCE_ID
          FROM ROLE_RESOURCE RR, ADMIN A, ADMIN_ROLE AR, RESOURCES R
         WHERE RR.ROLE_ID = AR.ROLE_ID
           AND A.ADMIN_ID = AR.ADMIN_ID
           AND RR.RESOURCE_ID = R.RESOURCE_ID
           AND R.MODULE_CODE IN (:moduleCode)
           AND R.RESOURCE_TYPE = 'M'
           AND A.OPERATOR_ID = :operateId) U
 WHERE M.RESOURCE_ID = U.RESOURCE_ID
 ORDER BY M.PARENT_RESOURCE_ID ASC, M.SEQ ASC