SELECT R.RESOURCE_ID
FROM OPERATOR_RESOURCE O, RESOURCES R
WHERE O.RESOURCE_ID = R.RESOURCE_ID
	AND R.MODULE_CODE IN (:moduleCode)
	AND O.OPERATOR_ID = :operateId
UNION
SELECT R.RESOURCE_ID
FROM ROLE_RESOURCE RR, ADMIN A, ADMIN_ROLE AR, RESOURCES R
WHERE RR.ROLE_ID = AR.ROLE_ID
   	AND A.ADMIN_ID = AR.ADMIN_ID
   	AND RR.RESOURCE_ID = R.RESOURCE_ID
   	AND R.MODULE_CODE IN (:moduleCode)
   	AND A.OPERATOR_ID = :operateId