SELECT UR.RESOURCE_ID, 
       UR.DIRECTORY_CODE, 
       UR.RESOURCE_NAME, 
       UR.URL, UR.METHOD, 
       UR.EVENT_ID, 
       UR.REMARK
FROM URL_RESOURCE UR, RESOURCES R
WHERE UR.RESOURCE_ID = R.RESOURCE_ID
AND R.MODULE_CODE IN (:moduleCode)