SELECT UR.RESOURCE_ID, UR.DIRECTORY_CODE, UR.RESOURCE_NAME, UR.URL, UR.METHOD, UR.EVENT_ID, UR.REMARK
  FROM URL_RESOURCE UR,
       (SELECT O.RESOURCE_ID
          FROM OPERATOR_RESOURCE O, RESOURCES R
         WHERE O.RESOURCE_ID = R.RESOURCE_ID
           AND R.MODULE_CODE IN (:moduleCode)
           AND R.RESOURCE_TYPE = 'U'
           AND O.OPERATOR_ID = :operateId
        UNION
        SELECT RR.RESOURCE_ID
          FROM ROLE_RESOURCE RR, ADMIN A, ADMIN_ROLE AR, RESOURCES R
         WHERE RR.ROLE_ID = AR.ROLE_ID
           AND A.ADMIN_ID = AR.ADMIN_ID
           AND RR.RESOURCE_ID = R.RESOURCE_ID
           AND R.MODULE_CODE IN (:moduleCode)
           AND R.RESOURCE_TYPE = 'U'
           AND A.OPERATOR_ID = :operateId) U
 WHERE UR.RESOURCE_ID = U.RESOURCE_ID