SELECT R.RESOURCE_ID
FROM OPERATOR_RESOURCE O, RESOURCES R
WHERE O.RESOURCE_ID = R.RESOURCE_ID
	AND R.MODULE_CODE IN (:moduleCode)
	AND O.OPERATOR_ID = :operateId
UNION
SELECT R.RESOURCE_ID
FROM  OPERATOR_ROLE O, ROLE_RESOURCE RR, RESOURCES R
WHERE RR.ROLE_ID = O.ROLE_ID
     AND RR.RESOURCE_ID = R.RESOURCE_ID
     AND R.MODULE_CODE IN (:moduleCode)
     AND O.OPERATOR_ID = 1