project: #项目信息
  name: framework-ai-demo
  model: dev

spring:
  application:
    name: ${project.name}
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      
logging:
  level:
    root: debug