SELECT  M.RESOURCE_ID, 
		M.PARENT_RESOURCE_ID, 
		M.MODULE_CODE, 
		M.FUNCTION_ID, 
		M.SEQ, 
		M.MENU_NAME, 
		M.URL, 
		M.IS_LEAF, 
		M.ICON_URL,
		M.TYPE,
		(SELECT MM.MENU_NAME FROM MENU MM WHERE MM.RESOURCE_ID = M.PARENT_RESOURCE_ID) AS PARENT_MENU_NAME,
		(SELECT F.FUNCTION_NAME FROM FUNCTION F WHERE F.FUNCTION_ID = M.FUNCTION_ID) AS FUNCTION_NAME,
		(SELECT MODULE_NAME FROM MODULE WHERE MODULE_CODE = M.MODULE_CODE) AS MODULE_NAME
FROM MENU M
WHERE 1=1
#if($type)
	AND M.TYPE = :type
#end
#if($moduleCodes)
	AND M.MODULE_CODE IN :moduleCodes
#end
#if($menuResourceId)
	AND M.PARENT_RESOURCE_ID = :menuResourceId
#end
ORDER BY M.PARENT_RESOURCE_ID ASC, M.SEQ ASC