SELECT  M.RESOURCE_ID, 
		M.PARENT_RESOURCE_ID, 
		M.MODULE_CODE, 
		M.FUNCTION_ID, 
		M.SEQ, 
		M.MENU_NAME, 
		M.URL, 
		M.IS_LEAF, 
		M.ICON_URL,
		M.TYPE,
		(SELECT MM.MENU_NAME FROM MENU MM WHERE MM.RESOURCE_ID = M.PARENT_RESOURCE_ID) AS PARENT_MENU_NAME,
		(SELECT MODULE_NAME FROM MODULE WHERE MODULE_CODE = M.MODULE_CODE) AS MODULE_NAME
FROM MENU M
WHERE 1=1
  AND M.RESOURCE_ID = :id