SELECT 	U.RESOURCE_ID, 
		U.FUNCTION_ID, 
		U.RESOURCE_NAME, 
		U.URL, 
		U.METHOD, 
		U.EVENT_ID
FROM URL_RESOURCE U
WHERE 1 = 1
#if($functionId)
AND U.FUNCTION_ID LIKE :functionId
#end
ORDER BY U.RESOURCE_NAME ASC