SELECT R.RESOURCE_ID,
       R.FUNCTION_ID,
       R.RESOURCE_NAME,
       R.URL,
       R.METHOD,
       R.EVENT_ID
  FROM URL_RESOURCE R, FUNCTION F, MENU M
 WHERE 1 = 1
	 AND R.FUNCTION_ID = F.FUNCTION_ID
	 AND F.FUNCTION_ID = M.FUNCTION_ID
	 AND M.MODULE_CODE IN :moduleCodes