project: #项目信息
 name: tx-demo-client3
 server:
   transaction: tx-demo-server
 server-url:
   transaction: http://localhost:8937
    
server.port: 8939
 
spring: #应用配置
  application:
    name: ${project.name} 
  data:
    cassandra:
      keyspace-name: sgp_tx
      contactPoints: 127.0.0.1
      port: 9042
    
feign:
  hystrix:
    enabled: true