SELECT D.DUTY_ID,
       D.DUTY_NAME,
       D.ORG_ID,
       D.OPERATOR_ID,
       D.CREATE_TIME,
       D.EXT,
       (SELECT O.ORG_NAME FROM ORG O WHERE O.ORG_ID = D.ORG_ID) AS ORG_NAME
  FROM DUTY D
  WHERE 1=1
    AND D.STATE = 'A'
  #if($orgId)
    AND D.ORG_ID = :orgId
  #end
  ORDER BY D.DUTY_ID ASC