INSERT INTO CONFIG_ITEM_HISTORY
(
    CONFIG_ITEM_ID,
    SEQ,
    MODULE_CODE,
    CONFIG_ITEM_CODE,
    CONFIG_ITEM_NAME,
    IS_VISIABLE,
    UPDATE_TIME,
    REMARK,
    OPERATOR_ID,
    CHANNEL_ID
)
VALUES
(
    :itemHisPojo.configItemId,
    :itemHisPojo.seq,
    :itemHisPojo.moduleCode,
    :itemHisPojo.configItemCode,
    :itemHisPojo.configItemName,
    :itemHisPojo.isVisiable,
    CURRENT_TIMESTAMP(),
    :itemHisPojo.remark,
    :itemHisPojo.operatorId,
    :itemHisPojo.channelId
)