INSERT INTO TASK_HISTORY (
	TASK_ID, SEQ, TASK_NAME, TASK_STATE, CLASS_NAME, CREATE_TIME, IS_CONCURRENT, LAST_EXECUTE_TIME,
	METHOD, MODULE_CODE, NEXT_EXCUTE_DATE, OPERATOR_ID, PRIORITY, UPDATE_TIME, UPDATE_OPERATOR_ID
)
SELECT 
	TASK_ID, (SELECT COUNT(*) + 1 FROM TASK_HISTORY WHERE TASK_ID = :taskId ) AS SEQ,
	TASK_NAME, TASK_STATE, CLASS_NAME, CREATE_TIME, IS_CONCURRENT, LAST_EXECUTE_TIME, METHOD,
	MODULE_CODE, NEXT_EXCUTE_DATE, OPERATOR_ID, PRIORITY, NOW() AS UPDATE_TIME, :operatorId AS UPDATE_OPERATOR_ID
FROM 
	TASK 
WHERE 
	TASK_ID = :taskId