SELECT 
    ST.TRIGGER_ID, ST.TRIGGER_NAME, ST.CREATE_TIME, ST.OPERATOR_ID, TT.TRIGGER_TYPE
FROM 
    SIMPLE_TRIGGER ST, TASK_TRIGGER TT 
WHERE 
    ST.TRIGGER_ID = TT.TRIGGER_ID 
    AND TT.TRIGGER_TYPE = 1 
    AND TT.TASK_ID = :taskId
UNION
SELECT 
    CT.TRIGGER_ID, CT.TRIGGER_NAME, CT.CREATE_TIME, CT.OPERATOR_ID, TT.TRIGGER_TYPE
FROM 
    CRON_TRIGGER CT, TASK_TRIGGER TT 
WHERE 
    CT.TRIGGER_ID = TT.TRIGGER_ID 
    AND TT.TRIGGER_TYPE = 2 
    AND TT.TASK_ID = :taskId