project: #项目信息
  name: framework-ai-jmanus
  version: 4.1
  model: dev

spring:
  application:
    name: ${project.name}
  ai:
    openai:
      api-key: ms-375d4f20-87a5-4f25-a090-2568666c502f
      base-url: https://api-inference.modelscope.cn/v1/
      chat:
        options:
          model: Qwen/Qwen3-Coder-480B-A35B-Instruct
          temperature: 0.7
      embedding:
        enabled: false  

# AI模型配置示例
ai:
  models:
    configs:
      - baseUrl: "https://api.openai.com/v1"
        apiKey: "your-openai-api-key"
        modelName: "gpt-4"
        modelDescription: "OpenAI GPT-4模型"
        type: "openai"
        temperature: 0.7
        topP: 0.9
        completionsPath: "/chat/completions"
      - baseUrl: "https://api.anthropic.com/v1"
        apiKey: "your-anthropic-api-key"
        modelName: "claude-3"
        modelDescription: "Anthropic Claude-3模型"
        type: "anthropic"
        temperature: 0.8
        topP: 0.95
        completionsPath: "/messages"
