project: #项目信息
  name: framework-ai-jmanus
  version: 4.1
  model: dev

spring:
  application:
    name: ${project.name}
  ai:
    openai:
      api-key: ms-375d4f20-87a5-4f25-a090-2568666c502f
      base-url: https://api-inference.modelscope.cn/v1/
      chat:
        options:
          model: Qwen/Qwen3-Coder-480B-A35B-Instruct
          temperature: 0.7
      embedding:
        enabled: false
    ollama:
      chat:
        enabled: false
      embedding:
        enabled: false
    retry:
      max-attempts: 3
  flyway:
    #是否启用
    enabled: true
    # 可以支持多个location, 用','隔开
    # locations: classpath:db/migration
    #是否创建元数据表
    validate-on-migrate: true
    # flyway 的 clean 命令会删除指定 schema 下的所有 table, 生产务必禁掉。这个默认值是false 理论上作为默认配置是不科学的。
    # clean-disabled: false
    # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: true
    # 版本控制日志表，默认flyway_schema_history,不同系统建议修改数据
    table: t_flyway_history
    url: ${master.db.url}
    user: ${master.db.username}
    password: ${master.db.password}
    driverClassName: com.mysql.jdbc.Driver
    
logging:
  level:
    root: INFO
    com.hbasesoft.framework.ai.jmanus: DEBUG
  
master: #主数据库配置
  db:
    type: mysql
    url: jdbc:mysql://localhost:3306/framework-202508?useUnicode=true&characterEncoding=UTF-8&generateSimpleParameterMetadata=true&serverTimezone=Asia/Shanghai
    username: framework
    password: framework
    hibernate:
      ddl-auto: update

# 搜索引擎配置
SERP_API_KEY: 7682d39bea014d638900f7726e678aa5
