SELECT A.MESSAGE_TEMPLATE_ID,
       A.MESSAGE_TEMPLATE_CODE,
       A.TEMPLATE,
       A.NAME,
       A.CONTACT_CHANNEL_IDS,
       A.STATE_TIME,
       A.STATE,
       A.DELAY,
       A.RESEND_TIMES,
       A.SAVE_HISTORY,
       A.SAVE_DAY,
       A.CREATE_TIME
  FROM MESSAGE_TEMPLATE A
 WHERE A.MESSAGE_TEMPLATE_ID = :messageTemplateId