INSERT INTO TASK
  (TASK_NAME,
   CLASS_NAME,
   METHOD,
   MODULE_CODE,
   PRIORITY,
   IS_CONCURRENT,
   TASK_STATE,
   LAST_EXECUTE_TIME,
   NEXT_EXCUTE_DATE,
   OPERATOR_ID,
   CREATE_TIME)
VALUES
  (:pojo.taskName,
   :pojo.className,
   :pojo.method,
   :pojo.moduleCode,
   :pojo.priority,
   :pojo.isConcurrent,
   :pojo.taskState,
   :pojo.lastExecuteTime,
   :pojo.nextExcuteDate,
   :pojo.operatorId,
   sysdate())