SELECT D.DIRECTORY_CODE,
       D.DIRECTORY_NAME,
       D.PARENT_DIRECTORY_CODE,
       D.REMARK,
       (SELECT COUNT(DD.DIRECTORY_CODE) FROM DIRECTORY DD WHERE DD.PARENT_DIRECTORY_CODE = D.DIRECTORY_CODE ) as CHILD_NUM
  FROM DIRECTORY D
 WHERE 1 = 1
   AND D.PARENT_DIRECTORY_CODE = :parentDirectoryCode
