project:
 name: framework-job-core

server: #系统配置
  port: 8063

job:
  register:
    url: 192.168.10.75:2181
    namespace: framework-job-core
  event:
    enable: false
  FooJob: true
    
master: #主数据库配置
 db:
  type: mysql
  url: jdbc:mysql://192.168.10.73:3306/vcc-sgp-system?useUnicode=true&characterEncoding=UTF-8&generateSimpleParameterMetadata=true&serverTimezone=Asia/Shanghai
  username: vcc-sgp-dev
  password: vcc-sgp-dev