SELECT
	o.USER_NAME,
	c.ACCOUNT_TYPE,
	a.ADMIN_NAME,
	a.GENER,
	a.EMAIL,
	a.PHONE,
	a.ADDRESS,
	a.CREATE_TIME,
	o.OPERATOR_ID,
	a.ADMIN_ID
FROM
	OPERATOR o,
	ADMIN a,
	ACCOUNT c
WHERE
	1 = 1
AND o.OPERATOR_ID = a.OPERATOR_ID
AND c.OPERATOR_ID = o.OPERATOR_ID
AND o.OPERATOR_ID = :operatorId