SELECT
	O.USER_NAME,
	C.ACCOUNT_TYPE,
	A.ADMIN_NAME,
	A.GENER,
	A.EMAIL,
	A.PHONE,
	A.ADDRESS,
	A.CREATE_TIME,
	O.OPERATOR_ID,
	A.ADMIN_ID
FROM
	T_MANAGER_OPERATOR O,
	T_MANAGER_ADMIN A,
	T_MANAGER_ACCOUNT C
WHERE
	1 = 1
AND O.OPERATOR_ID = A.OPERATOR_ID
AND C.OPERATOR_ID = O.OPERATOR_ID
AND O.OPERATOR_ID = :operatorId