SELECT O.OPERATOR_ID,
       O.OPERATOR_TYPE,
       O.OPERATOR_CODE,
       O.DUTY_ID,
       O.USER_NAME,
       O.PASSWORD,
       O.CREATE_DATE,
       O.STATE,
       O.STATE_DATE,
       O.IS_LOCKED,
       O.PWD_EXP_DATE,
       O.REGIST_IP,
       O.LAST_IP,
       O.LAST_LOGIN_DATE,
       O.LOGIN_FAIL
FROM T_MANAGER_OPERATOR O, T_MANAGER_ACCOUNT A
WHERE O.OPERATOR_ID = A.OPERATOR_ID
AND O.STATE = 'A'
AND A.STATE = 'A'
AND A.ACCOUNT_VALUE = :account
AND A.ACCOUNT_TYPE = :accountType
