project: #项目信息
 name: log-demo2
 
server: #系统配置
  port: 8081

spring: #应用配置
  application:
    name: ${project.name}
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0
      
cache.model: SIMPLE
