<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.hbasesoft.framework</groupId>
		<artifactId>framework</artifactId>
		<version>4.2.0</version>
	</parent>
	<artifactId>framework-ai</artifactId>
	<name>framework-ai</name>
	<description>AI人工智能框架</description>
	<packaging>pom</packaging>
	<properties>
		<spring-ai.version>1.1.2</spring-ai.version>
		<alibaba-ai.version>1.1.0.0-RC2</alibaba-ai.version>
	</properties>
	<modules>
		<module>framework-ai-demo</module>
		<module>framework-ai-agent</module>
	</modules>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.ai</groupId>
				<artifactId>spring-ai-bom</artifactId>
				<version>${spring-ai.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<dependency>
				<groupId>com.alibaba.cloud.ai</groupId>
				<artifactId>spring-ai-alibaba-agent-framework</artifactId>
				<version>${alibaba-ai.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
</project>