project: #项目信息
 name: db-demo
  
spring: #应用配置
  application:
    name: ${project.name}
  
master: #主数据库配置
 db:
  type: mongodb # mongodb
  url: jdbc:h2:./target/test
 mongodb:
  url: mongodb://localhost:27017/test01?retryWrites=false
#mongodb:
# uri: mongodb://localhost:27017/test01