SELECT RR.ROLE_ID, RR.RESOURCE_ID, RR.RESOURCE_TYPE, RR.RESOURCE_CODE
  FROM T_MANAGER_ROLE_RESOURCE RR, T_MANAGER_ROLE R, T_MANAGER_DUTY_ROLE DR
 WHERE RR.ROLE_ID = R.ROLE_ID
   AND R.ROLE_ID = DR.ROLE_ID
   AND R.MODULE_CODE = :moduleCode
   AND DR.DUTY_ID = :dutyId
