SELECT RR.ROLE_ID, RR.RESOURCE_ID, RR.RESOURCE_TYPE
  FROM ROLE_RESOURCE RR, ROLE R, DUTY_ROLE DR
 WHERE 1 = 1
   AND RR.ROLE_ID = R.ROLE_ID
   AND R.ROLE_ID = DR.ROLE_ID
   AND R.MODULE_CODE = :moduleCode
   AND DR.DUTY_ID = :dutyId
