SELECT ATTR_ID,
       ATTR_NAME,
       ATTR_TYPE,
       PARENT_ATTR_ID,
       ATTR_CODE,
       VISIBLE,
       INSTANTIATABLE,
       DEFAULT_VALUE,
       INPUT_TYPE,
       DATA_TYPE,
       VALUE_SCRIPT
FROM   ATTR
WHERE  PARENT_ATTR_ID = :attrId